{"uuid": "e419a3e2-c4c1-4e14-88a8-15251dcf9cbe", "counter": 35, "stdout": "fatal: [BEL1NA]: FAILED! => {\"ansible_facts\": {\"discovered_interpreter_python\": \"/usr/local/bin/python3.7\"}, \"changed\": false, \"msg\": \"Failed to authenticate: Authentication failed.\"}\r\n...ignoring", "start_line": 29, "end_line": 31, "runner_ident": "2d4b63cf-aacd-4785-beaa-5fa5f0c8838f", "event": "runner_on_failed", "pid": 1845223, "created": "2020-11-02T16:02:33.878700", "parent_uuid": "0242ac1a-000b-2a46-e349-000000000019", "event_data": {"playbook": "main.yaml", "playbook_uuid": "24c0d039-4990-4904-b950-701a5aeca994", "play": "Interfaces", "play_uuid": "0242ac1a-000b-2a46-e349-000000000007", "play_pattern": "EQUIPOS", "task": "ASR SHOW INTERFACES", "task_uuid": "0242ac1a-000b-2a46-e349-000000000019", "task_action": "cli_command", "task_args": "", "task_path": "/usr/local/ansible/mejoras_cu1/yaml/oc.yaml:15", "host": "BEL1NA", "remote_addr": "BEL1NA", "res": {"msg": "Failed to authenticate: Authentication failed.", "invocation": {"module_args": {"command": "show int desc | exc '\"'", "newline": true, "sendonly": false, "check_all": false, "prompt": null, "answer": null}}, "ansible_facts": {"discovered_interpreter_python": "/usr/local/bin/python3.7"}, "warnings": ["Platform linux on host BEL1NA is using the discovered Python interpreter at /usr/local/bin/python3.7, but future installation of another Python interpreter could change this. See https://docs.ansible.com/ansible/2.9/reference_appendices/interpreter_discovery.html for more information."], "_ansible_no_log": false, "changed": false}, "start": "2020-11-02T16:02:07.149530", "end": "2020-11-02T16:02:33.878537", "duration": 26.729007, "ignore_errors": true, "event_loop": null, "uuid": "e419a3e2-c4c1-4e14-88a8-15251dcf9cbe"}}